apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-platform-observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: agentkube
  source:
    repoURL: 'https://github.com/SudoAnirudh/AgentKube.git'
    targetRevision: HEAD
    path: observability
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
