apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-platform-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: agentkube
  source:
    repoURL: 'https://github.com/SudoAnirudh/AgentKube.git'
    targetRevision: HEAD
    path: charts/agent-platform
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: agent-platform
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
